name: frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install Node 20 if not installed
            if ! command -v node > /dev/null
            then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            # Install Nginx if not installed
            if ! command -v nginx > /dev/null
            then
              sudo apt update
              sudo apt install -y nginx
            fi

            # Clone repo only if not exists
            if [ ! -d "/home/ubuntu/mini-todo-app" ]; then
              git clone https://github.com/manav142003/mini-todo-app.git /home/ubuntu/mini-todo-app
            fi

            cd /home/ubuntu/mini-todo-app
            git pull origin main

            cd mini-todo-frontend
            npm install
            npm run build

            # Create nginx config FIRST
            sudo tee /etc/nginx/sites-available/mini-todo > /dev/null << 'EOF'
            server {
                listen 80;
                server_name _;

                root /home/ubuntu/mini-todo-app/mini-todo-frontend/dist;
                index index.html;

                location / {
                    try_files $uri $uri/ /index.html;
                }
            }
            EOF

            # Enable config
            sudo ln -sf /etc/nginx/sites-available/mini-todo /etc/nginx/sites-enabled/mini-todo
            sudo rm -f /etc/nginx/sites-enabled/default

            # Fix permissions
            sudo chown -R ubuntu:ubuntu /home/ubuntu/mini-todo-app/mini-todo-frontend/dist
            sudo chmod 755 /home/ubuntu

            # Test & restart
            sudo nginx -t
            sudo systemctl restart nginx
            sudo systemctl enable nginx